# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'db_table': 'redirect_code',
            },
        ),
    ]
