# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:32
from __future__ import unicode_literals
from getpass import getpass

from django.contrib.auth.models import User
from django.db import migrations


def create_admin_user(apps, schema_editor):
    admin_user = User.objects.create(username='admin', is_staff=True, is_superuser=True)
    while True:
        print('\n\n\nCreating superuser for admin page with username admin.')
        password1 = getpass('\n\nPassword: ')
        password2 = getpass('Confirm password: ')
        if password1 == password2:
            admin_user.set_password(password1)
            admin_user.save()
            break


def delete_admin_user(apps, schema_editor):
    admin_user = User.objects.filter(username='admin').first()
    if admin_user:
        admin_user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, delete_admin_user)
    ]
